<?php

function acf_banner()
{
    return array(
        array(
            'key' => 'field_6182f6e2311d4',
            'label' => 'Banner',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_6182f6f9311d5',
            'label' => 'Heading',
            'name' => 'banner_heading',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_619e6495384ec',
            'label' => 'Background Image',
            'name' => 'stats_background_image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_619e64ad384ed',
            'label' => 'Parallax',
            'name' => 'stats_bg_is_parallax',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_619e69dfc15a5',
            'label' => 'Overlay',
            'name' => 'stats_overlay',
            'type' => 'select',
            'instructions' => '*sets the opacity for the overlay to make text more readable on bright images',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                0 => 'none',
                '.125' => 'very light',
                '.25' => 'light',
                '.5' => 'normal',
                '.75' => 'heavy',
            ),
            'default_value' => false,
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        array(
            'key' => 'field_61a8f7aa6cbef',
            'label' => 'Content Type',
            'name' => 'banner_content_type',
            'type' => 'true_false',
            'instructions' => '*choose between stats and mass times for the content of the banner',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => 'Mass Times',
            'ui_off_text' => 'Stats',
        ),
        array(
            'key' => 'field_6182f712311d6',
            'label' => 'Stat Items',
            'name' => 'stat_items',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_61a8f7aa6cbef',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_6182f720311d7',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => '',
            'sub_fields' => array(
                array(
                    'key' => 'field_623c9c0518dc7',
                    'label' => 'Icon',
                    'name' => 'stat_item_icon',
                    'type' => 'font-awesome',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'icon_sets' => '',
                    'custom_icon_set' => '',
                    'default_label' => '',
                    'default_value' => '',
                    'save_format' => 'element',
                    'allow_null' => 0,
                    'show_preview' => 1,
                    'enqueue_fa' => 0,
                    'fa_live_preview' => '',
                    'choices' => array(),
                ),
                array(
                    'key' => 'field_6182f731311d8',
                    'label' => 'Content',
                    'name' => 'stat_item_content',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => 35,
                    'rows' => 2,
                    'new_lines' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_61a8f8226cbf0',
            'label' => 'Mass Times',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_61a8f7aa6cbef',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '*Mass Times can be set in <a href="/wp-admin/admin.php?page=theme-general-settings">Theme Settings > Theme Settings > Mass Times</a>',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        array(
            'key' => 'field_62434adb17370',
            'label' => 'Link',
            'name' => 'mass_times_link',
            'type' => 'link',
            'instructions' => '*Link to the full schedule',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_61a8f7aa6cbef',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
    );
}