<?php

function acf_mission()
{
    return  array(
        array(
            'key' => 'field_6182f5c8311cc',
            'label' => 'Mission',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_6182f5e7311cd',
            'label' => 'Mission Header',
            'name' => 'mission_header',
            'type' => 'text',
            'instructions' => '*Max 30 Characters',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => 30,
        ),
        array(
            'key' => 'field_6182f5e7311cx',
            'label' => 'Mission Header (faded text)',
            'name' => 'mission_header_faded',
            'type' => 'text',
            'instructions' => '*Max 30 Characters. This will display above the header as scrolling text.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => 30,
        ),
        // array(
        //     'key' => 'field_623a1c6e4f924',
        //     'label' => 'Content Position',
        //     'name' => 'mission_content_position',
        //     'type' => 'select',
        //     'instructions' => '',
        //     'required' => 0,
        //     'conditional_logic' => 0,
        //     'wrapper' => array(
        //         'width' => '50',
        //         'class' => '',
        //         'id' => '',
        //     ),
        //     'choices' => array(
        //         'left' => 'Left',
        //         // 'center' => 'Center',
        //         'right' => 'Right',
        //     ),
        //     'default_value' => false,
        //     'allow_null' => 0,
        //     'multiple' => 0,
        //     'ui' => 1,
        //     'ajax' => 0,
        //     'return_format' => 'value',
        //     'placeholder' => '',
        // ),
        array(
            'key' => 'field_6182f608311ce',
            'label' => 'Mission Content',
            'name' => 'mission_content',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        array(
            'key' => 'field_6182f50e311cy',
            'label' => 'Button',
            'name' => 'mission_button',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
        array(
            'key' => 'field_623a114b91882',
            'label' => 'Image',
            'name' => 'mission_background_image',
            'type' => 'image',
            'instructions' => '*Recommended size 600x600',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        )
    );
}
